production:
  adapter: postgresql
  encoding: unicode
  database: eigopost_db
  pool: 5
  username: brockpatterson
  password: \\\\

development:
  adapter: postgresql
  encoding: unicode
  database: eigopost_db
  pool: 5
  username: brockpatterson
  password: \\\\

test:
  adapter: postgresql
  encoding: unicode
  database: eigopost_db
  pool: 5
  username: brockpatterson
  password: \\\\
