development:
  adapter: postgresql
  encoding: unicode
  database: eigopost_db
  pool: 5
  username: bcp
  password: !!!!

test:
  adapter: postgresql
  encoding: unicode
  database: eigopost_db
  pool: 5
  username: bcp
  password: !!!!
